server:
  port: 8087

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Surendra4Sur/config-server-spring3.git
          refresh-rate: 1

  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka/

  management:
    endpoints:
      web:
        exposure:
          include: refresh

  logging:
    level:
      org:
        springframework: DEBUG
